spring.application.name=ProductDemo_S8

server.port=8071

# MySQL database connection URL, including the database name
spring.datasource.url=jdbc:mysql://localhost:3306/productdb
# MySQL database username
spring.datasource.username=root
# MySQL database password
spring.datasource.password=WELCOME@123RKC
# The driver class name for MySQL Connector/J
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA and Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
